"""ad relationship Animal ConsumoAnimal

Revision ID: 0218dbae3496
Revises: f19275dcac64
Create Date: 2024-05-30 22:05:52.465954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0218dbae3496'
down_revision: Union[str, None] = 'f19275dcac64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
