"""changes db add default value for qtd atribute ConsumoAnimal

Revision ID: 0615fb7e311a
Revises: 4ecd4f2ebd75
Create Date: 2024-06-01 03:02:41.514682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0615fb7e311a'
down_revision: Union[str, None] = '4ecd4f2ebd75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
