"""add id_usario to Animal and id_animal to ConsumoAnimal

Revision ID: 373bb49a86f7
Revises: e4243119e8e4
Create Date: 2024-05-30 21:42:19.196248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '373bb49a86f7'
down_revision: Union[str, None] = 'e4243119e8e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('id_usuario', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'animal', ['id_usuario'])
    op.create_foreign_key(None, 'animal', 'usuarios', ['id_usuario'], ['id_usuario'])
    op.add_column('consumo_animal', sa.Column('id_animal', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'consumo_animal', ['id_animal'])
    op.create_foreign_key(None, 'consumo_animal', 'animal', ['id_animal'], ['id_animal'])
    op.drop_constraint('usuarios_id_animal_key', 'usuarios', type_='unique')
    op.drop_constraint('usuarios_id_animal_fkey', 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'id_animal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('id_animal', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('usuarios_id_animal_fkey', 'usuarios', 'animal', ['id_animal'], ['id_animal'])
    op.create_unique_constraint('usuarios_id_animal_key', 'usuarios', ['id_animal'])
    op.drop_constraint(None, 'consumo_animal', type_='foreignkey')
    op.drop_constraint(None, 'consumo_animal', type_='unique')
    op.drop_column('consumo_animal', 'id_animal')
    op.drop_constraint(None, 'animal', type_='foreignkey')
    op.drop_constraint(None, 'animal', type_='unique')
    op.drop_column('animal', 'id_usuario')
    # ### end Alembic commands ###
