"""changes db add default value for qtd atribute ConsumoAnimal

Revision ID: 4ecd4f2ebd75
Revises: 65325393b477
Create Date: 2024-06-01 02:59:33.634215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ecd4f2ebd75'
down_revision: Union[str, None] = '65325393b477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
