"""exclude table Animal and relationships

Revision ID: 5e43c72cb983
Revises: dc9dd1647b7b
Create Date: 2024-05-30 23:31:46.483124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e43c72cb983'
down_revision: Union[str, None] = 'dc9dd1647b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status_animal', sa.Column('id_usuario', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'status_animal', 'usuarios', ['id_usuario'], ['id_usuario'])
    op.drop_column('status_animal', 'id_animal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status_animal', sa.Column('id_animal', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'status_animal', type_='foreignkey')
    op.drop_column('status_animal', 'id_usuario')
    # ### end Alembic commands ###
