"""add qtd(float) em ConsumoAnimal table

Revision ID: ed45af5c6d84
Revises: 81e6032d553c
Create Date: 2024-05-30 20:53:11.099435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed45af5c6d84'
down_revision: Union[str, None] = '81e6032d553c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumo_animal', sa.Column('qtd', sa.Float(), nullable=True))
    op.alter_column('consumo_animal', 'alimento',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consumo_animal', 'alimento',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.drop_column('consumo_animal', 'qtd')
    # ### end Alembic commands ###
