"""changes db

Revision ID: 65325393b477
Revises: 9de5365fde6a
Create Date: 2024-05-31 11:09:06.141941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65325393b477'
down_revision: Union[str, None] = '9de5365fde6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alimento_status_grupo_alimento', table_name='alimento_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_alimento_status_grupo_alimento', 'alimento_status', ['grupo_alimento'], unique=False)
    # ### end Alembic commands ###
