"""exclude resistencia from tables status, alimento_status

Revision ID: e4243119e8e4
Revises: ed45af5c6d84
Create Date: 2024-05-30 20:57:55.358091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4243119e8e4'
down_revision: Union[str, None] = 'ed45af5c6d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alimento_status', 'resistencia')
    op.drop_column('status_animal', 'resistencia')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status_animal', sa.Column('resistencia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('alimento_status', sa.Column('resistencia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
