"""add id_usario to Animal and id_animal to ConsumoAnimal

Revision ID: f19275dcac64
Revises: 373bb49a86f7
Create Date: 2024-05-30 21:59:10.179300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19275dcac64'
down_revision: Union[str, None] = '373bb49a86f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
